In [5]:
datadir = r"C:\Users\jagadesh\Jupyter Projects\DataSets\Playing cards_YOLO"

In [4]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Dropout , Activation , Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.layers import Input , Dense , Flatten, Conv2D, AveragePooling2D
from tensorflow.keras.models import Model
import os
import matplotlib.pyplot as plt
import numpy as np
import random
from sklearn.model_selection import train_test_split
import cv2
from keras.optimizers import SGD
import pickle
import pandas as pd
import tensorflow as tf
import os.path
from os import path

from matplotlib import image
from matplotlib import pyplot
from PIL import Image
from numpy import asarray

from keras.utils.np_utils import to_categorical
import matplotlib.pyplot as plt
import matplotlib.patches as patches

#from keras.models import Sequential
# #from keras.layers import Conv2D, MaxPool2D, Flatten, Dense
# from keras.layers.normalization import BatchNormalization
# from sklearn.model_selection import train_test_split
# from keras.optimizers import Adam

In [220]:
label = []
X_vector = []
IMG_SIZE = 120
for filename in os.listdir(datadir):
    if filename.endswith('jpg') or filename.endswith('JPG') :  
            image_filename = os.path.join(datadir , filename)
            filename_txt = filename[:-4]
            filename_txt = filename_txt + '.txt'
            label_filename =os.path.join(datadir , filename_txt)
            if os.path.exists(image_filename) and os.path.exists(label_filename): 
                image = cv2.imread(image_filename,cv2.IMREAD_GRAYSCALE)
                image_vector = cv2.resize(image,(IMG_SIZE,IMG_SIZE))
                #print(image_vector)
                X_vector.append(image_vector)
                label_file = open(os.path.join(datadir , filename_txt))
                label_text = label_file.read()
                #fdf= print(label_text.split())
                
                label.append(label_text.split())

X_vector_array = np.array(X_vector)
X = X_vector_array
y = np.array(label)

In [53]:
# label = []
# X_vector = []
# IMG_SIZE = 60
# for filename in os.listdir(datadir):
#     #print(filename)
#   #  try:
#         if filename.endswith('jpg') or filename.endswith('JPG') :  
#             image_filename = os.path.join(datadir , filename)
#             filename_txt = filename[:-4]
#             filename_txt = filename_txt + '.txt'
#             label_filename =os.path.join(datadir , filename_txt)
#             if os.path.exists(image_filename) and os.path.exists(label_filename): 

#     #             image = Image.open(image_filename)
#                 #image = i
#                 #new_array = cv2.resize(img_array,(IMG_SIZE,IMG_SIZE))
#                 # convert image to numpy array
#                 image = cv2.imread(image_filename,cv2.IMREAD_GRAYSCALE)
#                 #image_vector = asarray(image)
#                 image_vector = cv2.resize(image,(IMG_SIZE,IMG_SIZE))
#                 print(image_vector)
#                 X_vector.append(image_vector)
#                 #filename.endswith('txt'):
#                 label_file = open(os.path.join(datadir , filename_txt))
#                 label_text = label_file.read()
#                 print(label_text.split())
#                 label.append(label_text.split())
# #     except:
# #         print('error')
# #         pass
                   
        


In [221]:
# #type(image_vector)
# #print(image_vector.shape)
# X_vector_array = np.array(X_vector)
# X = X_vector_array
# y = np.array(label)
# #print(X_vector_array.shape)
# # print(X.shape)
#print(y.shape)
#print(X[1])
#print(y[1])
#y = np.transpose(y)
print(X.shape)
print(y.shape)


(51, 120, 120)
(51, 5)


In [223]:
# import random
# z = []
# for i in range(51):
#     z.append(random.randrange(1, 4))
#     random.randrange(3, 9)
# print(z)
# len(z)
# z = np.array(z)
# print(z.shape)

In [224]:
#X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.10, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.10, random_state=42)

In [225]:
y_train


array([['16', '0.202899', '0.423469', '0.231884', '0.193878'],
       ['16', '0.229167', '0.430233', '0.270833', '0.209302'],
       ['18', '0.209184', '0.441176', '0.255102', '0.205882'],
       ['18', '0.217172', '0.439850', '0.272727', '0.203008'],
       ['16', '0.227723', '0.452555', '0.237624', '0.204380'],
       ['15', '0.238095', '0.451852', '0.247619', '0.207407'],
       ['17', '0.215278', '0.422680', '0.263889', '0.206186'],
       ['17', '0.207143', '0.426316', '0.271429', '0.200000'],
       ['15', '0.229592', '0.447368', '0.275510', '0.203008'],
       ['15', '0.188172', '0.438849', '0.290323', '0.201439'],
       ['16', '0.247525', '0.443609', '0.237624', '0.195489'],
       ['17', '0.247525', '0.438406', '0.257426', '0.181159'],
       ['18', '0.224490', '0.439850', '0.265306', '0.203008'],
       ['16', '0.208333', '0.429630', '0.250000', '0.192593'],
       ['18', '0.204082', '0.444444', '0.265306', '0.207407'],
       ['16', '0.230392', '0.442308', '0.245098', '0.20

In [226]:
y_ind_train=[]
y_bb_train= []
y_ind_test=[]
y_bb_test= []
for i in y_train:
    #print(i[0])
    k = int(i[0]) - 15
    y_ind_train.append(k)
    y_bb_train.append([float(i[1]),float(i[2]),float(i[3]),float(i[4])])
for i in y_test:
    #print(i[0])
    t = int(i[0]) - 15
    y_ind_test.append(t)
    y_bb_test.append([float(i[1]),float(i[2]),float(i[3]),float(i[4])])
y_bb_train = np.array(y_bb_train)
y_ind_train = np.array(y_ind_train)
y_bb_test = np.array(y_bb_test)
y_ind_test = np.array(y_ind_test)

In [227]:
y_bb_train = np.array(y_bb_train)
y_ind_train = np.array(y_ind_train)
print(type(y_ind_train[1]))
print(type(y_bb_train[1][1]))
#print(y_bb_train)
#print(y_ind_train)


<class 'numpy.int32'>
<class 'numpy.float64'>


In [234]:
inputs = Input(shape = (120,120,1))
h = Conv2D (1,(3,3), activation = 'relu')(inputs)
h = Conv2D (10,(3,3), activation = 'relu')(h)
#h = AveragePooling2D(3)(h)
h = Flatten()(h)

outputs = Dense(5,activation = 'softmax',name = 'outputs')(h)
aux_output = Dense(4,activation = 'linear',name = 'aux_output')(h)

model_func = Model(inputs = inputs, outputs = [outputs,aux_output])

model_func.compile(loss = ['sparse_categorical_crossentropy', 'mse'], loss_weights = [1,0.5],metrics = ['accuracy'])

history = model_func.fit([X_train],[y_ind_train,y_bb_train],epochs=250)



Epoch 1/250
2/2 [==============================] - 0s 43ms/step - loss: 617520.2500 - outputs_loss: 507.2388 - aux_output_loss: 1234025.8750 - outputs_accuracy: 0.2667 - aux_output_accuracy: 0.2222
Epoch 2/250
2/2 [==============================] - 0s 33ms/step - loss: 1725.3899 - outputs_loss: 1423.0017 - aux_output_loss: 604.7764 - outputs_accuracy: 0.2444 - aux_output_accuracy: 0.0222
Epoch 3/250
2/2 [==============================] - 0s 34ms/step - loss: 983.8659 - outputs_loss: 888.0440 - aux_output_loss: 191.6438 - outputs_accuracy: 0.2222 - aux_output_accuracy: 0.1778
Epoch 4/250
2/2 [==============================] - 0s 35ms/step - loss: 288.2577 - outputs_loss: 209.5701 - aux_output_loss: 157.3752 - outputs_accuracy: 0.3333 - aux_output_accuracy: 0.1556
Epoch 5/250
2/2 [==============================] - 0s 37ms/step - loss: 98.4099 - outputs_loss: 33.5213 - aux_output_loss: 129.7773 - outputs_accuracy: 0.7111 - aux_output_accuracy: 0.1333
Epoch 6/250
2/2 [=====================

2/2 [==============================] - 0s 35ms/step - loss: 19.7558 - outputs_loss: 1.0596e-08 - aux_output_loss: 39.5116 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.1111
Epoch 86/250
2/2 [==============================] - 0s 33ms/step - loss: 19.7610 - outputs_loss: 1.0596e-08 - aux_output_loss: 39.5219 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.0667
Epoch 87/250
2/2 [==============================] - 0s 34ms/step - loss: 28.4737 - outputs_loss: 1.3245e-08 - aux_output_loss: 56.9474 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.2444
Epoch 88/250
2/2 [==============================] - 0s 34ms/step - loss: 68.0830 - outputs_loss: 1.3245e-08 - aux_output_loss: 136.1661 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.2444
Epoch 89/250
2/2 [==============================] - 0s 34ms/step - loss: 300.5876 - outputs_loss: 2.9140e-08 - aux_output_loss: 601.1751 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.0222
Epoch 90/250
2/2 [==============================] 

2/2 [==============================] - 0s 34ms/step - loss: 0.4427 - outputs_loss: 0.0082 - aux_output_loss: 0.8689 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.7333
Epoch 171/250
2/2 [==============================] - 0s 32ms/step - loss: 0.4370 - outputs_loss: 0.0230 - aux_output_loss: 0.8279 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.5111
Epoch 172/250
2/2 [==============================] - 0s 32ms/step - loss: 0.2536 - outputs_loss: 0.0364 - aux_output_loss: 0.4345 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.8667
Epoch 173/250
2/2 [==============================] - 0s 34ms/step - loss: 0.1047 - outputs_loss: 0.0162 - aux_output_loss: 0.1769 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.5778
Epoch 174/250
2/2 [==============================] - 0s 36ms/step - loss: 0.0807 - outputs_loss: 0.0075 - aux_output_loss: 0.1463 - outputs_accuracy: 1.0000 - aux_output_accuracy: 0.9333
Epoch 175/250
2/2 [==============================] - 0s 34ms/step - loss: 0.213

In [235]:
model_func.predict(
    X_test,
    batch_size=None,
    verbose=0,
    steps=None,
    callbacks=None,
    max_queue_size=10,
    workers=1,
    use_multiprocessing=False,
)


[array([[0.45761466, 0.02303416, 0.50658286, 0.00835378, 0.00441453],
        [0.04562824, 0.04721447, 0.8864938 , 0.01548522, 0.00517828],
        [0.03157895, 0.11846177, 0.78484964, 0.06143775, 0.00367193],
        [0.3943616 , 0.19354694, 0.1615402 , 0.17270553, 0.07784583],
        [0.580114  , 0.21826479, 0.08968448, 0.06576475, 0.04617203],
        [0.59421796, 0.23408502, 0.0918722 , 0.06250272, 0.01732213]],
       dtype=float32),
 array([[0.20053189, 0.2004594 , 0.0888264 , 0.15228635],
        [0.12771568, 0.259968  , 0.07597116, 0.1038437 ],
        [0.3081777 , 0.28256342, 0.16082308, 0.18284208],
        [0.05818503, 0.03453708, 0.0026738 , 0.02921082],
        [0.08558907, 0.1395348 , 0.03776018, 0.02899485],
        [0.19897105, 0.12637135, 0.12397493, 0.04137605]], dtype=float32)]

In [236]:
loss, main_loss, aux_loss, main_acc, aux_acc = model_func.evaluate(X_test,
                                (y_ind_test, y_bb_test),
                                batch_size=5)

2/2 [==============================] - 0s 4ms/step - loss: 1.4543 - outputs_loss: 1.4367 - aux_output_loss: 0.0352 - outputs_accuracy: 0.5000 - aux_output_accuracy: 0.3333


In [ ]:
fig2 = plt.figure()
ax2 = fig2.add_subplot(111, aspect='equal')

ax2.add_patch(
     patches.Rectangle(
        (0.1, 0.1),
        0.5,
        0.5,
        fill=False      # remove background
     ) ) 
fig2.savefig('rect2.png', dpi=90, bbox_inches='tight')

In [193]:
sevenspade = r"C:\Users\jagadesh\Jupyter Projects\DataSets\Playing cards_YOLO/7s.jpg"

In [200]:
seven_image = cv2.imread(sevenspade,cv2.IMREAD_GRAYSCALE)
seven_vector = cv2.resize(seven_image,(IMG_SIZE,IMG_SIZE))
seven_vector = np.array(seven_vector)
#print(image_vector)
#seven_vector.append(seven_vector)
print(seven_vector.shape)
                
print(X_train[1].shape)
                

(60, 60)
(60, 60)


In [245]:
predicted_1 = model_func.predict(
    X_train,
    batch_size=None,
    verbose=0,
    steps=None,
    callbacks=None,
    max_queue_size=10,
    workers=1,
    use_multiprocessing=False,
)
print(predicted_1)

[array([[3.35458571e-05, 9.99952197e-01, 5.38255608e-06, 6.12747044e-06,
        2.86341788e-06],
       [1.02117956e-04, 9.99777496e-01, 5.65133414e-05, 3.96363284e-05,
        2.41600046e-05],
       [3.13730038e-06, 2.97325550e-06, 1.90143226e-06, 9.99988437e-01,
        3.56564124e-06],
       [2.49994810e-06, 3.59681940e-06, 2.44502417e-06, 9.99990344e-01,
        1.04691787e-06],
       [4.24971631e-06, 9.99978662e-01, 7.64881042e-06, 6.04926436e-06,
        3.36196854e-06],
       [9.99830127e-01, 7.51042971e-05, 3.97764816e-05, 3.49644033e-05,
        2.00488430e-05],
       [6.12932417e-05, 4.47141210e-05, 9.99881268e-01, 8.62021716e-06,
        4.18800528e-06],
       [2.22280505e-06, 4.21672257e-06, 9.99992490e-01, 5.92554386e-07,
        5.07122422e-07],
       [9.90242541e-01, 3.00813396e-03, 2.45598471e-03, 2.64184945e-03,
        1.65150070e-03],
       [9.99898195e-01, 3.21887128e-05, 3.13628880e-05, 2.54998922e-05,
        1.27553276e-05],
       [3.42002431e-06, 9.999

In [246]:
y_ind_train

array([1, 1, 3, 3, 1, 0, 2, 2, 0, 0, 1, 2, 3, 1, 3, 1, 0, 3, 1, 3, 3, 0,
       2, 0, 3, 1, 2, 2, 1, 1, 2, 0, 0, 3, 2, 2, 2, 2, 3, 0, 3, 3, 2, 1,
       3])

In [207]:
y_bb_test[1]
X_test[4]

array([0.242574, 0.441606, 0.247525, 0.19708 ])

In [1]:
from PIL import Image
import numpy as np

w, h = 60 , 60
#data = np.zeros((h, w, 3), dtype=np.uint8)
#data[0:256, 0:256] = [255, 0, 0] # red patch in upper left
img = Image.fromarray(X_test[1])
img.save('my.png')
img.show()

NameError: name 'X_test' is not defined

In [ ]:
c=- 0
d= - 0
h = 
s= - 0

In [ ]:
# for c in contours:
#     # get the bounding rect
#     x, y, w, h = cv2.boundingRect(c)
#     # draw a green rectangle to visualize the bounding rect
#     cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

In [ ]:
from PIL import Image, ImageDraw, ImageFont
# get an image
im = Image.open('image.jpg').convert('RGBA')

draw = ImageDraw.Draw(im)
draw.rectangle(((200, 200), (100, 100)), outline="#ff8888")
del draw
im.show()
